hr:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: hr_management_system
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  minio:
    endpoint: http://192.168.6.152:9000
    access-key: f9bzYmfHr5uCN7TEbM95
    secret-key: pPIUXalNfizVk5yFsFdvPIHFkxFjCZPvyIFpCI1A
    bucket-name: hr_management_system
